---
title: "Hertie Coding Club Impressum"
page-layout: full
toc: true
include-in-header: meta.html
comments: false
---

<style>
  body {
  background: linear-gradient(to right, black, black);
  color: white !important;
}

nav#TOC.toc-active h2#toc-title, nav#TOC.toc-active ul{
color: white;
}

</style>

<hr>



# Information {style="color: white;"}

Hertie Coding Club

- Affiliated School: Hertie School

- Address: Friedrichstraße 180, 10117 Berlin
- Phone: +49 30 2592190
- Email: hertiecodingclub@gmail.com


#  Club Leaders or Authorized Representatives {style="color: white;"}

- Club President: Jorge Roa

- Advisory Teacher: Simon Munzert

<hr>

#  Responsible for Content {style="color: white;"}

- Jorge Roa 

- Address: Friedrichstraße 180, 10117 Berlin

- Phone: +49 30 2592190

- Email: jurjoo@gmail.com

# Website {style="color: white;"}

Domain: www.hertiecodingclub.com

Hosting: Google

# Disclaimer {style="color: white;"}

<hr>

All the information on this website - www.hertiecodingclub.com - is published in good faith and for general information purpose only. Hertie Coding Club does not make any warranties about the completeness, reliability, and accuracy of this information. Any action you take upon the information you find on this website (www.hertiecodingclub.com), is strictly at your own risk. Hertie Coding Club will not be liable for any losses and/or damages in connection with the use of our website.

